# Generated by Django 4.2.7 on 2023-11-25 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('idProducts', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=255)),
                ('forSize', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='name',
        ),
        migrations.AddField(
            model_name='pricelist',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricelist',
            name='status',
            field=models.CharField(default='в наличии', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricelist',
            name='idProducts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.products'),
            preserve_default=False,
        ),
    ]
